import SMicons from '@/Components/SocialMedia/SMicons'
import Navbar from '@/Navbar/Navbar'
import { Box, Container, Typography } from '@mui/material'
import Head  from 'next/head'
import React, { useRef, useState } from 'react'
import emailjs from '@emailjs/browser';

const Index = () => {
  const ref = useRef();
  const form = useRef();
  const [status,
      setStatus] = useState(0)
  const [email,
      setEmail] = useState('')
  const sendEmail = async(e : any) => {

    e.preventDefault();

    if (!form.current) 
        return;
    let regexEmail = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;
    if (!email.match(regexEmail)) {
        setStatus(400)
        return;
    }

    const req = await emailjs.sendForm(`service_fvka279`, 'template_veigfx8', form.current, 'lbTdA9-5crCdl733u')
    const res = await req
    setStatus(res ? res.status : 400)
};

  return (
    <>
    <Head>
    <title>Contact Page</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <Navbar dark/>
  <main>
    <Container maxWidth='xl' >
        <Box sx={{my:4}}>
        <Typography sx={{fontSize:{xs:'2em'},my:3,fontWeight:'800'}}>
        Reach us at:
        </Typography>
        
        <Typography className='clr' sx={{fontSize:{xs:'1.35em'},fontWeight:'500'}}>
            Lebanon/Beirut
        </Typography>
        <Typography className='clr' sx={{fontSize:{xs:'1.35em'},fontWeight:'500'}}>
            @onbeirut
        </Typography>
        <Typography className='clr' sx={{fontSize:{xs:'1.35em'},fontWeight:'500'}}>
            +961 71 920 255
        </Typography>
        <Typography className='clr' sx={{fontSize:{xs:'1.35em'},fontWeight:'500'}}>    
        onbeirut@gmail.com
        </Typography>
        <Typography sx={{fontSize:{xs:'2em'},my:3,fontWeight:'800'}}>
        Social media:
        </Typography>
        <SMicons color='black' sx={{'a':{borderColor:'black'},mt:2.5}}/>
        </Box>
    </Container>
  </main>
    </>
  )
}

export default Index