import Goal from '@/Components/Home/Goal'
import Hero from '@/Components/Home/Hero'
import Navbar from '@/Navbar/Navbar'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero/>
        <Goal/>
      </main>
    </>
  )
}
